Upgraded to pgx v5 and bump package major version to v3
pckhoi/casbin-pgx-adapter pull request #11
Opened 2022-12-12 17:20 UTC by niallnsec

This pull requests updates the pgx dependency to the v5 branch as v4 is out of support. I have also bumped the package version to v3 as this is a breaking change.

2022-12-13 01:43 UTC, hsluoyz commented
@pckhoi plz review

2022-12-13 01:54 UTC, pckhoi requested changes
Thanks for your contribution. But please replace `QueryFunc` invocations with `ForEachRow`, and `pool.BeginFunc` with `pgx.BeginFunc`. Using shortcuts mean there are less chance of introducing bugs and it will also make it easier for me as the reviewer to spot errors. Unless you have other reasons.

2022-12-13 01:54 UTC, pckhoi commented on adapter.go
> +	}
Could have replaced with `ForEachRow`.

2022-12-13 01:54 UTC, pckhoi commented on adapter.go
> +		tx.Rollback(context.Background())
Should replace with `pgx.BeginFunc`.

2022-12-13 13:13 UTC, niallnsec commented
Sorry, my bad. I saw that the functions used previously had been removed and didn't see the top level funcs in the pgx package to replace them, which is why I reverted to the more explicit approach.

I've changed it so that it mirrors more appropriately your existing implementation.

2022-12-13 13:20 UTC, niallnsec commented on adapter.go
> +	}
Updated with latest commits

2022-12-13 13:20 UTC, niallnsec commented on adapter.go
> +		tx.Rollback(context.Background())
Updated with latest commits

2022-12-14 03:31 UTC, pckhoi commented
@hsluoyz how do you feel about bumping this adapter to v3 while still using casbin v2?

2022-12-14 03:53 UTC, hsluoyz commented
@pckhoi it's OK. Adapter version and Casbin version are not related. See: https://github.com/casbin/redis-adapter

2022-12-14 05:48 UTC, pckhoi commented
@niallnsec looks like the Go version is incompatible with pgx v5. Please upgrade go version in go.mod to 1.18 and up.

2022-12-15 17:33 UTC, niallnsec commented
@pckhoi I already did update the go.mod version to 1.18

2022-12-15 17:36 UTC, niallnsec commented
I noticed the CI was failing because I hadn't bumped the Go version from 1.14 to 1.18, so I have now done that so hopefully the tests will run

2022-12-16 00:26 UTC, merged